services:
  mysql:
    image: mysql:9.1
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
      - mysql_data:/var/lib/mysql
  
  petclinic:
    image: elymoral/spring-petclinic:latest
    container_name: spring-petclinic
    depends_on:
      - mysql
    ports:
      - "8080:8080"

volumes:
  mysql_data:

